# Generated by Django 5.1.3 on 2024-11-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
    ]
